version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  reviewers:
  - tznind
  - jas88
- package-ecosystem: maven
  direction: "/nlp/uk.ac.dundee.hic.nerd"
  schedule:
    interval: daily
  reviewers:
  - jas88
