version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - jas88
      - rkm
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - jas88
      - rkm
  - package-ecosystem: maven
    directory: "/nlp/uk.ac.dundee.hic.nerd"
    schedule:
      interval: daily
    reviewers:
      - jas88
      - rkm
